on:
  push:
    branches: [ "main" ]
env:
  CR_URI: medegor44.cr.cloud.ru
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CR_URI }}
          username: ${{ secrets.EVO_CR_LOGIN }}
          password: ${{ secrets.EVO_CR_PWD }}
          
      - name: Go - Build and push docker image to Evolution Aritfact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CR_URI }}/echo-bot:${{ github.sha }}
          file: ./Dockerfile
          context: .

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{secrets.SSH_DEPLOY_KEY}}
          script: |
            sudo su
            docker login -u ${{ secrets.EVO_CR_LOGIN }} -p ${{ secrets.EVO_CR_PWD }}
            docker stop bot
            docker rm bot
            docker pull ${{ env.CR_URI }}/echo-bot:${{ github.sha }}
            docker run -e BOT_API_TOKEN=${{ secrets.BOT_API_TOKEN }} -n bot ${{ env.CR_URI }}/echo-bot:${{ github.sha }}